name: Bug report
description: Create a bug report to help us improve
title: '[Bug]: <Choose an appropriate title>'
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem
      placeholder: Currently, I am trying to [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: To reproduce
      description: Provide steps to reproduce the problem
      placeholder: 'Steps to reproduce the behaviour: [...]'
      value: |-
        Steps to reproduce the behaviour:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen
      placeholder: The app should [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: You can upload screenshots by drag’n’drop
  - type: textarea
    attributes:
      label: Logcat
      description: If the app crashes, a logcat of the error could be very helpful
      placeholder: Copy paste from the log/console
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here
  - type: markdown
    attributes:
      value: '# Environment'
  - type: input
    attributes:
      label: Device
      placeholder: e.g. Fairphone 5, 256 GB edition
    validations:
      required: true
  - type: input
    attributes:
      label: OS
      placeholder: e.g. Stock Android 7.0 or /e/OS 2.7
    validations:
      required: true
  - type: input
    attributes:
      label: FakeTraveler version
      placeholder: e.g. 2.0.0
    validations:
      required: true
