name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Generate and submit dependency graphs
        uses: gradle/actions/dependency-submission@v4
        with:
          dependency-graph: generate-and-submit
        if: github.event_name != 'pull_request'
      - name: Build with Gradle
        run: ./gradlew build
